//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursus()
        {
            this.Beoordelingen = new HashSet<Beoordeling>();
            this.Cursus_Bijzonderheden = new HashSet<Cursus_Bijzonderheid>();
            this.Cursussen_Student = new HashSet<Cursus_Student>();
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public System.DateTime Datum { get; set; }
        public int Categorie_Id { get; set; }
        public int Niveau_Id { get; set; }
        public decimal Prijs { get; set; }
        public int Taal_Id { get; set; }
        public string Code { get; set; }
        public string Beschrijving { get; set; }
        public int Lesgever_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beoordeling> Beoordelingen { get; set; }
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursus_Bijzonderheid> Cursus_Bijzonderheden { get; set; }
        public virtual Lesgever Lesgever { get; set; }
        public virtual Niveau Niveau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursus_Student> Cursussen_Student { get; set; }
        public virtual Taal Taal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
    }
}
