//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursus_Bijzonderheid
    {
        public int Id { get; set; }
        public int Cursus_Id { get; set; }
        public int Bijzonderheid_Id { get; set; }
    
        public virtual Bijzonderheid Bijzonderheid { get; set; }
        public virtual Cursus Cursus { get; set; }
    }
}
