//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ondertitel
    {
        public int Id { get; set; }
        public int Taal_Id { get; set; }
        public int Video_Id { get; set; }
        public string Filepath { get; set; }
    
        public virtual Taal Taal { get; set; }
        public virtual Video Video { get; set; }
    }
}
