//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Ondertitels = new HashSet<Ondertitel>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Filepath { get; set; }
        public int Taal_Id { get; set; }
        public int Cursus_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ondertitel> Ondertitels { get; set; }
        public virtual Taal Taal { get; set; }
        public virtual Cursus Cursus { get; set; }
    }
}
